---
server:
    install: '1'
    packages: [vim, git, npm]
    timezone: Europe/Paris
    locale: fr_FR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: mjmr.dev, ip: 10.0.0.13, memory: '1024', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www/mjmr/current/web
    servername: mjmr.dev
pgsql:
    install: '1'
    database: mjmrdb
    user: mjmr
    password: mjmr
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-pgsql]
composer:
    install: '1'

