---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - create_www_data_user
    - nginx
    - pgsql
    - php
    - composer
    - app

- hosts: dev
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - vagrant_local
